version: '3.8'

services:
  fittracker:
    build: .
    ports:
      - "8081:8081"
      - "19000:19000" 
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    command: npx expo start --host 0.0.0.0 --tunnel
